# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ee59e0d800ff60ef2abb90a262934a3fbec493f26c1ce50e50690df2b6ec78e5e66acf89e004e560b1cf0f16a8d2b4bb06caeab2ee142373e1b50a3e6cfcbf4

test:
  secret_key_base: 795a69b06053d104f8b6d70ec251420d9fccc87ba519423f20ef9f144fd5639c16f6746fd50bfb672f16c2438ac84d0164e9f597486f02109afec3ce357f8d1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
